### PR TITLE
Dynamic tags

### PR DESCRIPTION
**Pull request by cecton**
I found this feature. We can solve the dynamic tag everywhere with that

### CODE REVIEW

**Comment by nbrr** [comment]
It compiles without raising any king of warning whatever you put in there, I don't think we should be happy with that.

**Review by EstebanBorai — APPROVED** [review]
LGTM!

**Review by oScape — APPROVED** [review]
Awesome 💪

**Comment by cecton** [comment]
Someone said it might not be wise to allow any tag like that.

I personally find weird also to allow to customize the tag. For now the only relevance we found was for `<Tag>` and its only reason to be is to be inlined instead of a block.

**Review by nbrr — COMMENTED** [review]
Got lost in Github's interface, thought it had been submitted already:

It compiles without raising any kind of warning whatever you feed it, I don't think we should be happy with that.

**Comment by EstebanBorai** [comment]
> Someone said it might not be wise to allow any tag like that.
> 
> I personally find weird also to allow to customize the tag. For now the only relevance we found was for `<Tag>` and its only reason to be is to be inlined instead of a block.

It depends in what you are trying to accomplish.

Elements in HTML comes with default displays either `inline` or `block`, this affects how boxes are rendered in your DOM.
This is a good to have feature, but is never a golden bullet, for example, EmberJS lets you define the `tagName` of the component you wrapping your entire component, this brings flexibility when comes to how this component in the DOM affects other elements.

I would have a default tag and let the user change it if needed.

**Review by Yozhgoor — APPROVED** [review]

**Comment by cecton** [comment]
I just changed it to a more strict way (like it was).

I think it works for now and we are in early development anyway so we can change it later if we realize that it is not enough.

I don't see any reason to have this feature in every component. But feel free to change it when we finally need it somewhere.

**Pull request merged**
